### ISSUE TITLE
How does this work?

### ISSUE THREAD

**Issue by CombineSlayer24** [chikakoo/MVM-Randomizer#1]
I'm not sure where to ask this, but I'm wondering how can this be used to create random mvm missions?

**Comment by chikakoo** [comment]
Hello!

I just spent some time to update the readme and create a release for this. Please have a look - I can answer more questions here if you have them.

**Comment by CombineSlayer24** [comment]
Alright. I'll will defiantly let you know. Thanks. I don't know how .java scripts work, like how you would be able to build/compile it. Again, I will let you know. 'preciate it.

**Comment by CombineSlayer24** [comment]
After a few days of playing with this. This is extremely fun. As a mission creator, it does get boring playing your own missions, and something like this, really is good. I do have some ideas and maybe some problems/issues to point out, and there's a lot.

**Issues:**
• Sometimes at the very end of a wave, the final wavespawn takes really long to respawn the wave, which in that case, you would be waiting for that final wave to spawn, waiting for like, 10-20 seconds for that final wavespawn to respawn. (_I'm not entirely sure if this is something to do with the Low Spawn range/High Spawn range_)
• Giants always seems to spawn in pairs of 2's. I wouldn't really call it an issue, but it does become an issue when a powerful giant is picked (_i.e., Giant Deflector Heavy, Giant Burst Fire Soldier [Crits]_)
• Medics always seem to get clustered together, and almost never leave the spawn room, unless there are other robots. The only thing that can alleviate this is pairing them in a squad with a non-medic squad leader, but not sure how you be able to make a randomizable squad.
• When using randomized bots (not templates), in the console, an error log pops up about (_TFBotSpawner: attribute error: 'Context 'ItemAttributes': Attribute "clip rate bonus" in "attributes" did not match any attribute definitions'_) I think you meant clip size bonus. 

**Ideas:**
• "RandomSpawn" option.  In the "Wave" category, there could be another box option called "RandomSpawn %" which will have a random chance of giving a wavespawn the "RandomSpawn 1" option (35% by default, can be configured). This could make maps like Mannhattan and Decoy much better in flow (_Especially Decoy with the spawnbot_invasion, since robots would either just spawn all in one area, when they could all spawn in the other spawns since that's where the spawnbot_invasion is, at all other spawns_)
• More wavespawn support bots, rather than 1.  There can be up to 5 max support wavespawns. Can be configurable for each wave on how many max active Wavespawn support the waves should have. And the amount of Support wavespawns is also random, like 1 wave might have 35% chance of support robots, and 2 max at a time, but it can choose to either have only 1, or have 2.
• Option for "Equal Robot distribution". Would there be another option to enable "Equal Robot distribution? This option would make the robots spawning coming in equal pairs. (_I'm not sure how this could throw off everything, with other settings like spawn multiplier in "Map" category since if you have a high value, the spawncounts are drastically increased_).

If there's 11 total count of scouts, max active of 9, spawncount of 7, this wouldn't be equal distribution. If equal distribution is enabled, the random generator could generate wavespawns like this instead [ _12 total count of scouts, 6 max active, 3 spawncount_ ]

While again, I do like the complete random wavespawns, I think having an Equal distribution as a checkbox option could make the wave/mission more, in synch?  

That's my thoughts, if you feel like you kinda don't understand which point(s), feel free to quote that in a reply and I can try to go more in depth into it. I tried to send this yesterday, but my DNS server kept having issues picking up github.

**Comment by CombineSlayer24** [comment]
Whoops. Accidently pressed "Closed" instead of "Comment".

**Comment by chikakoo** [comment]
Hello, thanks for your feedback! A few of these I've been considering doing, but haven't got around to it. A note too - we didn't expect this to be used by someone else originally! I may be implementing some of what you're suggesting here, but probably not all of it (right away at least). I'll leave some notes on the issues side of things:

Issues:
- Long final wavespawn: Yup - that happens depending on how quickly you clear out all the other bots and how long between spawns the bots are. That's not too easy to get right 100% of the time with a randomizer. Maybe if the time between wavespawns, etc. was 100% configurable, it could be tweaked to your liking, but no plans for that currently.
- 2 giants spawning at once: That's actually configurable - the default settings were tweaked specifically for me and a friend. If you want to change the number of giants, go to Bot, choose Giant, and adjust the spawn ranges for each class/bot. Most are 2-3, which is why you see that issue). You can save your settings from the File menu if you'd like. It will load the settings with the name "default" first if you want to make yours the default.
- Clustered medics: I've never seen them not leave the spawn room, besides one case - are you playing with others? I wonder if it's a solo problem. They could be paired with a squad in the future (there's custom code for one of the community maps that does that to fix the spawn room problem, but didn't see it happen in any other case, so didn't bother to use it elsewhere).
- clip rate bonus: You're correct - that would happen if Demos spawn with Sticky Launchers - I've hard-coded the wrong value there. Will be fixing that!

I'll likely close this in the next few days as well since the original issue was getting this set up for you. Thanks again!

**Comment by CombineSlayer24** [comment]
Hey, no problem, I discovered this by searching in GitHub " TF2 MvM Randomizer". This, along with another I've found, if you were wondering.

For Long Spawns, I was mostly playing with RCBots2 (Which adds bots for red team in MvM), and they do shred through a lot of the wavespawns. So, that didn't cross my mind until reading. I understand now.

For 2 Giants. I didn't know that was configurable, good to know.

For Clustered Medics, this was actually a mistake on my part, I was heavily editing the spawns and what not, when I reverted back to defaults, they do seem to move around a lot more, they hardly idle, they sometimes still do, but it's nothing like last time, like 10 seconds.

Anyway, no problem. I didn't mean to derail the topic of the issue. I don't know how to label issues, apologies. I really do enjoy this Randomizer. It's very fun to play on. Can't wait to see more updates, can't wait for more to know about this project. I wish you the best of today.

**Comment by chikakoo** [comment]
Hello! Thanks for clarifying some of your issues.

I wanted to point out that I was actually mistaken in how the giant spawn count was configured. It's actually currently hard-coded to be 1-2 of them at once for giants (50% chance of either) - I definitely misremembered there! Ideally that would be configurable probably at either a giant/normal level, or at a specific bot level.

Also, I'll be releasing another version today or tomorrow that 
1. Fixes the clip rate bonus error
2. Adds your suggested setting to add a configurable RandomSpawn 1 to wave spawns

**Comment by CombineSlayer24** [comment]
Alrighty. nice. I think we can close down this issue. open more if needed. I'll also be uploading some Youtube videos showing this off.
